#!/usr/bin/env bash
# Installs nginx server
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo su
chmod -R 755 /var/www/html
echo "Hello World!" > /var/www/html/index.html
service nginx start
