#!/usr/bin/env bash
# This script displays the visitor IP along with the HTTP status code
# from the Apache log file using awk command.
# The exact format must be: OCCURENCE_NUMBER IP HTTP_CODE

awk '{ print $1 " " $9 }' apache-access.log | sort | uniq -c | sort -nr
