#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes:
#   display hours from 0 to 12
#   display minutes from 1 to 59
# -use the while loop (for and until are forbidden)

hour=0

while [ $hour -le 12 ]
do
    minute=1
    echo "Hour: $hour"
    while [ $minute -lt 60 ]
    do
	echo "$minute"
	((minute++))
    done
    ((hour++))
done
