#!/usr/bin/env bash
# This script displays:
#   The content of the current directory
#   in a list format
#   Where only the part of the name after the first dash is displayed
# -use the for loop (while and until are forbidden)
# -not display hidden files

FILES="$(ls)"

for file in $FILES
do
   echo "$file" | cut -d '-' -f2
done
