#!/usr/bin/env bash
# This script gives you information about the school file.

FILE="school"

# Check if the file exists
if [ -e "$FILE" ]
then
    echo "school file exists"

    # Check if the file empty
    if [ -s "$FILE" ]
    then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi

    # Check if the file is a regular file
    if [ -f "$FILE" ]
    then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi       
